version: "3"
services:
    nginx-react:
    image: romybijoy/farm_konnect_admin:latest
    container_name: farm_konnect_admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NODE_ENV: production
    env_file:
      - .env

